package LabPojos;
// Generated Apr 16, 2016 11:37:16 PM by Hibernate Tools 4.3.1



/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer hospitalId;

    public Doctor() {
    }

	
    public Doctor(int id) {
        this.id = id;
    }
    public Doctor(int id, String name, Integer hospitalId) {
       this.id = id;
       this.name = name;
       this.hospitalId = hospitalId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getHospitalId() {
        return this.hospitalId;
    }
    
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }




}


