package LabPojos;
// Generated Apr 17, 2016 5:31:00 PM by Hibernate Tools 4.3.1



/**
 * Students generated by hbm2java
 */
public class Students  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private String degree;

    public Students() {
    }

	
    public Students(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Students(int id, String name, String email, String degree) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.degree = degree;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }




}


